# Default configuration settings for the project
app:
  name: My Project
  version: 1.0.0
  environment: development

database:
  host: localhost
  port: 5432
  username: user
  password: password
  dbname: my_project_db

server:
  host: 0.0.0.0
  port: 3000

logging:
  level: info
  format: json

features:
  enableFeatureX: true
  enableFeatureY: false

api:
  baseUrl: /api/v1
  timeout: 5000

# Add any additional configuration settings below as needed.